site_name: NCAA March Madness Predictor
site_description: Documentation for the NCAA March Madness prediction project
site_author: Tim McDonnell
repo_url: https://github.com/tim-mcdonnell/march_madness
repo_name: tim-mcdonnell/march_madness

theme:
  name: material
  palette:
    primary: indigo
    accent: orange
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_source: true
            show_submodules: true
  - mkdocs-jupyter:
      include_source: True

nav:
  - Home: index.md
  - Installation: installation.md
  - User Guide:
    - Getting Started: user_guide/getting_started.md
    - Pipeline Usage: user_guide/pipeline_usage.md
    - Configuration: user_guide/configuration.md
  - Technical Reference:
    - Pipeline:
      - Architecture Overview: reference/pipeline/overview.md
      - Data Stage: reference/pipeline/data_stage.md
      - EDA Stage: reference/pipeline/eda_stage.md
      - Feature Engineering: reference/pipeline/feature_engineering.md
      - Model Development: reference/pipeline/model_development.md
      - Evaluation: reference/pipeline/evaluation.md
    - Data: 
      - Data Sources: reference/data/sources.md
      - Processing: reference/data/processing.md
      - Validation: reference/data/validation.md
    - Models:
      - Overview: reference/models/overview.md
      - Evaluation: reference/models/evaluation.md
  - API Reference:
    - Data: api/data.md
    - Pipeline: api/pipeline.md
    - Features: api/features.md
    - Models: api/models.md
    - Visualization: api/visualization.md
  - Developer Guide:
    - Contributing: contributing.md
    - Extending: developer_guide/extending.md
  - Methodology: methodology.md 