# NCAA March Madness Prediction Pipeline Configuration

# Data paths
data:
  # Input data directories
  raw_dir: "data/raw"
  processed_dir: "data/processed"
  
  # Output data directories
  feature_dir: "data/features"
  model_dir: "models"
  results_dir: "results"
  
  # Data selection
  years: [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025]
  categories: ["play_by_play", "player_box", "schedules", "team_box"]

# Feature engineering settings
features:
  team_stats:
    # Team statistics to include as features
    offensive: ["points", "field_goals_made", "field_goals_att", "three_points_made"]
    defensive: ["opp_points", "opp_field_goals_made", "blocks", "steals"]
    
  # Advanced metrics
  advanced_metrics: ["offensive_efficiency", "defensive_efficiency", "pace", "true_shooting_pct"]
  
  # Feature aggregation window (number of games)
  aggregation_window: 10

# Model settings
model:
  # Model type (options: "random_forest", "gradient_boosting", "neural_network")
  type: "gradient_boosting"
  
  # Training settings
  train_years: [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
  validation_years: [2024]
  test_years: [2025]
  
  # Hyperparameters
  hyperparameters:
    n_estimators: 100
    learning_rate: 0.1
    max_depth: 5
    min_samples_split: 10
    random_state: 42

# Evaluation settings
evaluation:
  metrics: ["accuracy", "log_loss", "brier_score"]
  
  # Tournament simulation settings
  simulation:
    n_simulations: 1000
    seed_method: "bracket"  # Options: "bracket", "random", "custom" 